stages:

  prepare:
    cmd: python -m hyped.stages.prepare
      -c ../../cls/imdb/distilbert_data.json
      -o ./dump/data/distilbert
    params:
      - ../../cls/imdb/distilbert_data.json:
    outs:
      - ./dump/data/distilbert

  train:
    cmd: python -m hyped.stages.train
      -c ../../cls/imdb/distilbert_run.json
      -d ./dump/data/distilbert
      -o ./dump/models/distilbert
    params:
      - ../../cls/imdb/distilbert_run.json:
    deps:
      - ./dump/data/distilbert
    outs:
      - ./dump/models/distilbert

  evaluate:
    cmd: python -m hyped.stages.test
      -c ../../cls/imdb/distilbert_run.json
      -m ./dump/models/distilbert/best-model
      -d ./dump/data/distilbert
      -o ./dump/scores/distilbert
      -s test
    params:
      - ../../cls/imdb/distilbert_run.json:
    deps:
      - ./dump/models/distilbert/best-model
      - ./dump/data/distilbert
    metrics:
      - ./dump/scores/distilbert/imdb-test.json:
          cache: true

