stages:

  prepare:
    cmd: python -m hyped.stages.prepare
      -c ../../configs/imdb_bert_data.json
      -o ./dump/data/bert
    params:
      - ../../configs/imdb_bert_data.json:
    outs:
      - ./dump/data/bert

  train:
    cmd: python -m hyped.stages.train
      -c ../../configs/imdb_bert_exp.json
      -d ./dump/data/bert
      -o ./dump/models/bert
    params:
      - ../../configs/imdb_bert_exp.json:
    deps:
      - ./dump/data/bert
    outs:
      - ./dump/models/bert

  evaluate:
    cmd: python -m hyped.stages.test
      -c ../../configs/imdb_bert_exp.json
      -m ./dump/models/bert/best-model
      -d ./dump/data/bert
      -o ./dump/scores/bert
      -s test
    params:
      - ../../configs/imdb_bert_exp.json:
    deps:
      - ./dump/models/bert/best-model
      - ./dump/data/bert
    metrics:
      - ./dump/scores/bert/imdb-test.json:
          cache: true

