stages:

  # ---------------
  # simple pipeline (prepare -> train -> evaluate)
  # ---------------
  # prepare all data splits in one stage
  # prepare -> train -> evaluate

  prepare:
    cmd: python -m hyped.scripts.prepare
      -c ../text_cls/imdb/distilbert_data.json
      -o ./dump/data/distilbert.bin
    deps:
      - ../text_cls/imdb/distilbert_data.json
    outs:
      - ./dump/data/distilbert.bin

  train:
    cmd: python -m hyped.scripts.train
      -c ../text_cls/imdb/distilbert_run.json
      -d ./dump/data/distilbert.bin
      -o ./dump/models/distilbert
    deps:
      - ../text_cls/imdb/distilbert_run.json
      - ./dump/data/distilbert.bin
    outs:
      - ./dump/models/distilbert

  evaluate:
    cmd: python -m hyped.scripts.evaluate
      -c ../text_cls/imdb/distilbert_run.json
      -m ./dump/models/distilbert/best-model
      -d ./dump/data/distilbert.bin
      -o ./dump/scores/distilbert
      -s test
    deps:
      - ../text_cls/imdb/distilbert_run.json
      - ./dump/models/distilbert/best-model
      - ./dump/data/distilbert.bin
    metrics:
      - ./dump/scores/distilbert/imdb-test.json:
          cache: true

  # -----------------
  # advanced pipeline
  # -----------------
  # prepare each data split in a separate stage

  adv-prepare-train:
    cmd: python -m hyped.scripts.prepare
      -s train
      -c ../text_cls/imdb/distilbert_data.json
      -o ./dump/data/distilbert_train.bin
    deps:
      - ../text_cls/imdb/distilbert_data.json
    outs:
      - ./dump/data/distilbert_train.bin
  
  adv-prepare-val:
    cmd: python -m hyped.scripts.prepare
      -s validation
      -c ../text_cls/imdb/distilbert_data.json
      -o ./dump/data/distilbert_val.bin
    deps:
      - ../text_cls/imdb/distilbert_data.json
    outs:
      - ./dump/data/distilbert_val.bin

  adv-prepare-test:
    cmd: python -m hyped.scripts.prepare
      -s test
      -c ../text_cls/imdb/distilbert_data.json
      -o ./dump/data/distilbert_test.bin
    deps:
      - ../text_cls/imdb/distilbert_data.json
    outs:
      - ./dump/data/distilbert_test.bin
  
  adv-train:
    cmd: python -m hyped.scripts.train
      -c ../text_cls/imdb/distilbert_run.json
      -d ./dump/data/distilbert_train.bin ./dump/data/distilbert_val.bin
      -o ./dump/models/distilbert_adv
    deps:
      - ../text_cls/imdb/distilbert_run.json
      - ./dump/data/distilbert_train.bin
      - ./dump/data/distilbert_val.bin
    outs:
      - ./dump/models/distilbert_adv
  
  adv-test:
    cmd: python -m hyped.scripts.evaluate
      -c ../text_cls/imdb/distilbert_run.json
      -m ./dump/models/distilbert_adv/best-model
      -d ./dump/data/distilbert_test.bin
      -o ./dump/scores/distilbert_adv
      -s test
    deps:
      - ../text_cls/imdb/distilbert_run.json
      - ./dump/models/distilbert_adv/best-model
      - ./dump/data/distilbert_test.bin
    metrics:
      - ./dump/scores/distilbert_adv/imdb-test.json:
          cache: true
