stages:

  prepare-train:
    cmd: python -m hyped.scripts.prepare
      -s train
      -c ../../cls/imdb/distilbert_data.json
      -o ./dump/data/distilbert_train
    params:
      - ../../cls/imdb/distilbert_data.json:
    outs:
      - ./dump/data/distilbert_train
  
  prepare-val:
    cmd: python -m hyped.scripts.prepare
      -s validation
      -c ../../cls/imdb/distilbert_data.json
      -o ./dump/data/distilbert_val
    params:
      - ../../cls/imdb/distilbert_data.json:
    outs:
      - ./dump/data/distilbert_val

  prepare-test:
    cmd: python -m hyped.scripts.prepare
      -s test
      -c ../../cls/imdb/distilbert_data.json
      -o ./dump/data/distilbert_test
    params:
      - ../../cls/imdb/distilbert_data.json:
    outs:
      - ./dump/data/distilbert_test
  
  train:
    cmd: python -m hyped.scripts.train
      -c ../../cls/imdb/distilbert_run.json
      -d ./dump/data/distilbert_train ./dump/data/distilbert_val
      -o ./dump/models/distilbert_adv
    params:
      - ../../cls/imdb/distilbert_run.json:
    deps:
      - ./dump/data/distilbert_train
      - ./dump/data/distilbert_val
    outs:
      - ./dump/models/distilbert_adv
  
  evaluate:
    cmd: python -m hyped.scripts.evaluate
      -c ../../cls/imdb/distilbert_run.json
      -m ./dump/models/distilbert_adv/best-model
      -d ./dump/data/distilbert_test
      -o ./dump/scores/distilbert_adv
      -s test
    params:
      - ../../cls/imdb/distilbert_run.json:
    deps:
      - ./dump/models/distilbert_adv/best-model
      - ./dump/data/distilbert_test
    metrics:
      - ./dump/scores/distilbert_adv/imdb-test.json:
          cache: true
